Universidade Federal do Pará - (UFPA)

Discente: Romário Silva

E-mail: eng.romariosilva@gmail.com

Implementação do modelo AHP (Analytic Hierarchy Process)

Problema: Identificação de municípios, a partir de aspectos demográficos, com maior e menor propensão à ocorrência de dengue

1. Importação das biblotecas necessárias: pyDecision (GitHub Repository: <https://github.com/Valdecy>) e numpy

In [1]:
!pip install pyDecision
import pandas as pd


In [2]:
# Required Libraries
import numpy as np
from sklearn.preprocessing import normalize
# AHP
from pyDecision.algorithm import ahp_method

2. Criação da matriz de comparação

In [3]:
# AHP

#g1 Densidade Populacional (DP)
#g2 PIB per capita (PIB)
#g3 Índice de Desenvolvimento Humano Municipal (IDHM)
#g4 Esgotamento Sanitário Adequado (ESA)

# Parameters
weight_derivation = 'mean' # 'mean'; 'geometric' or 'max_eigen'

# Dataset

dataset = np.array([
  #DP     PIB    IDHM    ES   ESA
  [1  ,     5,     3,     3,      1],   #DP
  [1/5,     1,   1/3,   1/3,    1/5],   #PIB
  [1/3,     3,     1,   1/5,    1/5],   #IDHM
  [1/3,     3,     5,     1,    1/3],   #ES
  [1  ,     5,     5,     3,      1],   #ESA
])

#DP 5 X PIB = Muito mais importante, hábito alimentar por humanos
#DP 3 x IDHM = Moderadamente mais importante
#DP 1 x ESA = Falta de saneamento gera potenciais criadouros

#PIB x 3 IDHM = Desenvolvimento geral mais importante que receita
#PIB x 5 ESA = Estrutura de saneamento mais importante que receita

#IDHM x 5 ESA =

#normalized_dataset = dataset / np.sqrt(np.sum(dataset**2))

#for i in range(len(normalized_dataset)):
#  for j in range(len(normalized_dataset[0])):
#    normalized_dataset[i,j] = round(normalized_dataset[i,j],2)

#normalized_dataset
dataset

array([[1.        , 5.        , 3.        , 3.        , 1.        ],
       [0.2       , 1.        , 0.33333333, 0.33333333, 0.2       ],
       [0.33333333, 3.        , 1.        , 0.2       , 0.2       ],
       [0.33333333, 3.        , 5.        , 1.        , 0.33333333],
       [1.        , 5.        , 5.        , 3.        , 1.        ]])

3. Utilização do função AHP


In [4]:
# Call AHP Function
weights, rc = ahp_method(dataset, wd = weight_derivation)

4. Cálculo dos Pesos (Vetor Eigen)

In [5]:
# Weigths
for i in range(0, weights.shape[0]):
  print('Peso '+str(i+1)+': ', round(weights[i], 4)*100,'%')


for i in range(0, weights.shape[0]):
  weights[i] = round(weights[i], 4)
weights

Peso 1:  32.33 %
Peso 2:  5.390000000000001 %
Peso 3:  9.24 %
Peso 4:  17.93 %
Peso 5:  35.120000000000005 %


array([0.3233, 0.0539, 0.0924, 0.1793, 0.3512])

5. Cálculo do Índice de consistência

In [6]:
# Consistency Ratio
print('RC: ' + str(round(rc, 4)))
if (rc > 0.10):
  print('A solução é inconsistente, as comparações par a par devem ser revisadas')
else:
  print('A solução é consistente')

RC: 0.0874
A solução é consistente


6. Inserção da matriz com as alternativas e os valores

In [7]:
alternativas=np.array([
    #DP        PIB        IDHM   ESA
    [ 187.21,  21122.55,  673,  53.00, 36.1], #Castanhal
    [ 101.75,  11242.38,  659,  18.00, 10.7], #Santa Isabel do Pará
    [1230.23,   20562.1,  746, 168.00, 67.9], #Belém
    [1070.74,  15576.91,  676,  21.00, 18.8], #Marituba
    [2512.20,  15201.46,  718,  64.00, 55.1], #Ananindeua
    [ 338.44,  26267.84,  665,  17.00, 17.4], #Benedives
    [  75.82,  10196.64,  627,   9.00, 10.6], #Santa Bárbara do Pará
    [  96.65,  58550.40,  662,  32.00, 27.8], #Barcarena
    ])

normalized_alternativas = alternativas / np.sqrt(np.sum(alternativas**2))

for i in range(len(normalized_alternativas)):
  for j in range(len(normalized_alternativas[0])):
    normalized_alternativas[i,j] = round(normalized_alternativas[i,j],5)

normalized_alternativas

array([[2.4800e-03, 2.7967e-01, 8.9100e-03, 7.0000e-04, 4.8000e-04],
       [1.3500e-03, 1.4886e-01, 8.7300e-03, 2.4000e-04, 1.4000e-04],
       [1.6290e-02, 2.7225e-01, 9.8800e-03, 2.2200e-03, 9.0000e-04],
       [1.4180e-02, 2.0625e-01, 8.9500e-03, 2.8000e-04, 2.5000e-04],
       [3.3260e-02, 2.0128e-01, 9.5100e-03, 8.5000e-04, 7.3000e-04],
       [4.4800e-03, 3.4780e-01, 8.8000e-03, 2.3000e-04, 2.3000e-04],
       [1.0000e-03, 1.3501e-01, 8.3000e-03, 1.2000e-04, 1.4000e-04],
       [1.2800e-03, 7.7524e-01, 8.7700e-03, 4.2000e-04, 3.7000e-04]])

In [8]:
nomealternativa=("Castanhal", "Santa Isabel do Pará", "Belém", "Marituba", "Ananindeua", "Benevides", "Santa Bárbara do Pará", "Barcarena")

7. Multiplicação do vetor de pesos com as alternativas

In [9]:
total = []
for i in range(len(normalized_alternativas)):
  total.append([normalized_alternativas[i]*weights])
total

[[array([0.00080178, 0.01507421, 0.00082328, 0.00012551, 0.00016858])],
 [array([4.364550e-04, 8.023554e-03, 8.066520e-04, 4.303200e-05,
         4.916800e-05])],
 [array([0.00526656, 0.01467428, 0.00091291, 0.00039805, 0.00031608])],
 [array([4.5843940e-03, 1.1116875e-02, 8.2698000e-04, 5.0204000e-05,
         8.7800000e-05])],
 [array([0.01075296, 0.01084899, 0.00087872, 0.0001524 , 0.00025638])],
 [array([1.448384e-03, 1.874642e-02, 8.131200e-04, 4.123900e-05,
         8.077600e-05])],
 [array([3.233000e-04, 7.277039e-03, 7.669200e-04, 2.151600e-05,
         4.916800e-05])],
 [array([4.1382400e-04, 4.1785436e-02, 8.1034800e-04, 7.5306000e-05,
         1.2994400e-04])]]

8. Função soma para totalização

In [10]:
def somalista(numeros):
   if len(numeros) == 1:
        return numeros[0]
   else:
        return numeros[0] + somalista(numeros[1:])

9. Valor final para cada alternativa

In [11]:
soma = []
somatotal = []
for i in range(len(total)):
  soma.append(somalista(total[i]))
  somatotal.append(round(sum(soma[i]),3))
print(somatotal)

[0.017, 0.009, 0.022, 0.017, 0.023, 0.021, 0.008, 0.043]


In [12]:
def maior_valor(lista):
    try:
        if len(lista) == 0:
            return None

        maior = lista[0]

        for valor in lista:
            if valor > maior:
                maior = valor

        return maior
    except TypeError:
        return lista

In [13]:
def menor_valor(lista):
    menor = 9999999
    try:
        if len(lista) == 0:
            return None
        menor = lista[0]

        for valor in lista:
            if valor < menor:
                menor = valor
        return menor
    except TypeError:
        return lista

In [14]:
maior = maior_valor(somatotal)
posmaior = somatotal.index(maior)
menor = menor_valor(somatotal)
posmenor = somatotal.index(menor)

In [15]:
print('O maior valor obtido foi:', maior, 'referente ao município:', nomealternativa[posmaior])
print('O menor valor obtido foi:', menor, 'referente ao município:', nomealternativa[posmenor])

O maior valor obtido foi: 0.043 referente ao município: Barcarena
O menor valor obtido foi: 0.008 referente ao município: Santa Bárbara do Pará
