Universidade Federal do Pará - (UFPA)

Discente: Romário da Costa Silva

E-mail: eng.romariosilva@gmail.com

Tarefa: Implementação do modelo AHP (Analytic Hierarchy Process)

Problema: Identificação de municípios, a partir de aspectos demográficos, com maior e menor propensão à ocorrência de dengue

1. Importação das biblotecas necessárias: pyDecision (GitHub Repository: <https://github.com/Valdecy>) e numpy

In [ ]:
!pip install pyDecision

     ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 104.6/104.6 kB 2.8 MB/s eta 0:00:00
     ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 220.8/220.8 kB 7.9 MB/s eta 0:00:00
     ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 2.0/2.0 MB 18.8 MB/s eta 0:00:00
     ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 48.9/48.9 kB 5.3 MB/s eta 0:00:00
     ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 75.0/75.0 kB 9.5 MB/s eta 0:00:00
     ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 76.9/76.9 kB 9.2 MB/s eta 0:00:00
     ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 2.7/2.7 MB 35.0 MB/s eta 0:00:00
     ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 58.3/58.3 kB 7.1 MB/s eta 0:00:00


In [ ]:
# Required Libraries
import numpy as np
from sklearn.preprocessing import normalize
# AHP
from pyDecision.algorithm import ahp_method

2. Criação da matriz de comparação

In [ ]:
# AHP

#g1 Densidade Populacional (DP)
#g2 PIB per capita (PIB)
#g3 Índice de Desenvolvimento Humano Municipal (IDHM)
#g4 Esgotamento Sanitário Adequado (ESA)

# Parameters
weight_derivation = 'mean' # 'mean'; 'geometric' or 'max_eigen'

# Dataset
dataset = np.array([
  #DP     PIB    IDHM   ESA
  [1  ,     5,     3,     1],   #DP
  [1/5,     1,   1/3,   1/5],   #PIB
  [1/3,     3,     1,   1/5],   #IDHM
  [1  ,     5,     5,     1],   #ESA
])

#DP 5 X PIB = Muito mais importante, hábito alimentar por humanos
#DP 3 x IDHM = Moderadamente mais importante
#DP 1 x ESA = Falta de saneamento gera potenciais criadouros

#PIB x 3 IDHM = Desenvolvimento geral mais importante que receita
#PIB x 5 ESA = Estrutura de saneamento mais importante que receita

#IDHM x 5 ESA =

#normalized_dataset = dataset / np.sqrt(np.sum(dataset**2))

#for i in range(len(normalized_dataset)):
#  for j in range(len(normalized_dataset[0])):
#    normalized_dataset[i,j] = round(normalized_dataset[i,j],2)

#normalized_dataset
dataset

array([[1.        , 5.        , 3.        , 1.        ],
       [0.2       , 1.        , 0.33333333, 0.2       ],
       [0.33333333, 3.        , 1.        , 0.2       ],
       [1.        , 5.        , 5.        , 1.        ]])

3. Utilização do função AHP


In [ ]:
# Call AHP Function
weights, rc = ahp_method(dataset, wd = weight_derivation)

4. Cálculo dos Pesos (Vetor Eigen)

In [ ]:
# Weigths
for i in range(0, weights.shape[0]):
  print('Peso '+str(i+1)+': ', round(weights[i], 4)*100,'%')


for i in range(0, weights.shape[0]):
  weights[i] = round(weights[i], 4)
weights

Peso 1:  37.25 %
Peso 2:  6.74 %
Peso 3:  13.41 %
Peso 4:  42.61 %


array([0.3725, 0.0674, 0.1341, 0.4261])

5. Cálculo do Índice de consistência

In [ ]:
# Consistency Ratio
print('RC: ' + str(round(rc, 4)))
if (rc > 0.10):
  print('A solução é inconsistente, as comparações par a par devem ser revisadas')
else:
  print('A solução é consistente')

RC: 0.0435
A solução é consistente


6. Inserção da matriz com as alternativas e os valores

In [ ]:
alternativas=np.array([
    #DP        PIB        IDHM   ESA
    [ 186.79,  21122.55,  673, 36.1], #Castanhal
    [ 101.75,  11242.38,  659, 10.7], #Santa Isabel do Pará
    [1230.23,   20562.1,  746, 67.9], #Belém
    [1070.74,  15576.91,  676, 18.8], #Marituba
    [2512.20,  15201.46,  718, 55.1], #Ananindeua
    [ 338.44,  26267.84,  665, 17.4], #Benedives
    [  75.82,  10196.64,  627, 10.6], #Santa Bárbara do Pará
    [  96.65,  58550.40,  662, 27.8], #Barcarena
    ])

normalized_alternativas = alternativas / np.sqrt(np.sum(alternativas**2))

for i in range(len(normalized_alternativas)):
  for j in range(len(normalized_alternativas[0])):
    normalized_alternativas[i,j] = round(normalized_alternativas[i,j],5)

normalized_alternativas

array([[2.4700e-03, 2.7968e-01, 8.9100e-03, 4.8000e-04],
       [1.3500e-03, 1.4886e-01, 8.7300e-03, 1.4000e-04],
       [1.6290e-02, 2.7226e-01, 9.8800e-03, 9.0000e-04],
       [1.4180e-02, 2.0625e-01, 8.9500e-03, 2.5000e-04],
       [3.3260e-02, 2.0128e-01, 9.5100e-03, 7.3000e-04],
       [4.4800e-03, 3.4780e-01, 8.8100e-03, 2.3000e-04],
       [1.0000e-03, 1.3501e-01, 8.3000e-03, 1.4000e-04],
       [1.2800e-03, 7.7524e-01, 8.7700e-03, 3.7000e-04]])

In [ ]:
nomealternativa=("Castanhal", "Santa Isabel do Pará", "Belém", "Marituba", "Ananindeua", "Benevides", "Santa Bárbara do Pará", "Barcarena")

7. Multiplicação do vetor de pesos com as alternativas

In [ ]:
total = []
for i in range(len(normalized_alternativas)):
  total.append([normalized_alternativas[i]*weights])
total

[[array([0.00092008, 0.01885043, 0.00119483, 0.00020453])],
 [array([5.0287500e-04, 1.0033164e-02, 1.1706930e-03, 5.9654000e-05])],
 [array([0.00606802, 0.01835032, 0.00132491, 0.00038349])],
 [array([0.00528205, 0.01390125, 0.00120019, 0.00010653])],
 [array([0.01238935, 0.01356627, 0.00127529, 0.00031105])],
 [array([1.668800e-03, 2.344172e-02, 1.181421e-03, 9.800300e-05])],
 [array([3.725000e-04, 9.099674e-03, 1.113030e-03, 5.965400e-05])],
 [array([0.0004768 , 0.05225118, 0.00117606, 0.00015766])]]

8. Função soma para totalização

In [ ]:
def somalista(numeros):
   if len(numeros) == 1:
        return numeros[0]
   else:
        return numeros[0] + somalista(numeros[1:])

9. Valor final para cada alternativa

In [ ]:
soma = []
somatotal = []
for i in range(len(total)):
  soma.append(somalista(total[i]))
  somatotal.append(round(sum(soma[i]),3))
print(somatotal)

[0.021, 0.012, 0.026, 0.02, 0.028, 0.026, 0.011, 0.054]


In [ ]:
def maior_valor(lista):
    try:
        if len(lista) == 0:
            return None

        maior = lista[0]

        for valor in lista:
            if valor > maior:
                maior = valor

        return maior
    except TypeError:
        return lista

In [ ]:
def menor_valor(lista):
    menor = 9999999
    try:
        if len(lista) == 0:
            return None
        menor = lista[0]

        for valor in lista:
            if valor < menor:
                menor = valor
        return menor
    except TypeError:
        return lista

In [ ]:
maior = maior_valor(somatotal)
posmaior = somatotal.index(maior)
menor = menor_valor(somatotal)
posmenor = somatotal.index(menor)

In [ ]:
print('O maior valor obtido foi:', maior, 'referente ao município:', nomealternativa[posmaior])
print('O menor valor obtido foi:', menor, 'referente ao município:', nomealternativa[posmenor])

O maior valor obtido foi: 0.054 referente ao município: Barcarena
O menor valor obtido foi: 0.011 referente ao município: Santa Bárbara do Pará
